name: Release package

on:
  push:
   branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: openssl, pdo, sqlite, pdo_sqlite

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.2-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.2-

    - name: Configure auth token
      run: composer config -g -a github-oauth.github.com ${{ secrets.ORG_GH_TOKEN_PACKAGES_RO }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run full test suite
      run: composer dev-tests

    - name: Release ${{ matrix.component }}
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ci: false
        tag_format: v${version}
        # you can set branches for semantic-release above v16.
